### ISSUE TITLE
Error while removing homologous kmers

### ISSUE THREAD

**Issue by peaceben** [marykthompson/ribopop_probe_design#2]
Hi Mary,

I'm a bit stuck. After a bit trail and error (and finally using Mamba instead of Conda, which worked like a charm) i could create the environment with all dependencies on a OS X 12.1 system. Unfortunately, the pipeline crashes with the following error:

Error in rule remove_homologous_kmers:
    jobid: 30
    output: probe_design/4.5S/potential_probes_filt.csv

RuleException:
CalledProcessError in line 149 of /Users/ben/Desktop/ribopop_probe_design/Snakefile:
Command 'set -euo pipefail;  /Users/ben/opt/anaconda3/envs/ribopop_probe_design/bin/python3.6 /Users/ben/Desktop/ribopop_probe_design/outdir/.snakemake/scripts/tmpy8e6jnzg.filter_probes.py' returned non-zero exit status 1.
  File "/Users/ben/Desktop/ribopop_probe_design/Snakefile", line 149, in __rule_remove_homologous_kmers
  File "/Users/ben/opt/anaconda3/envs/ribopop_probe_design/lib/python3.6/concurrent/futures/thread.py", line 56, in run

All steps before seem to work, as a list with potential probes is generated. Any intuitive ideas on what might causes the problem here?

Best,
Ben

PS: here's the snakemake log

[2022-01-10T183059.106163.snakemake.txt](https://github.com/marykthompson/ribopop_probe_design/files/7841153/2022-01-10T183059.106163.snakemake.txt)

**Comment by peaceben** [comment]
Your dependency list posted here ...

https://github.com/marykthompson/ribopop_probe_design/issues/1#issuecomment-790775687

... fixed it for me. Everything running quick and smooth now.

Cheers,
Ben

**Comment by marykthompson** [comment]
Thanks for solving your own problem:)
