### ISSUE TITLE
Problem During Pipeline execution

### ISSUE THREAD

**Issue by Aimepicornell** [marykthompson/ribopop_probe_design#3]
Dear Maryk Thompson, first of all: Thank you for sharing your method i really appreciate your work! 
After working through your workflow step by step i unfortunately run into an error which stops the pipeline from finishing. Maybe you will find some time to gibe me some tips to fix it
I tried running it with your example files, but unfortunately that also didn't work.

Thank you so much in advance!

Aimé Picornell

**Comment by Aimepicornell** [comment]
[2023-08-17T123234.279419.snakemake.log](https://github.com/marykthompson/ribopop_probe_design/files/12369473/2023-08-17T123234.279419.snakemake.log)

Some additional information: The same error happens even whe i use your files by  putting the designs_params folder in the same folder as the snakefile and the config.yml and start everything in my enviroment (conda activate ribopop_probe_design). Unfortunately i am clueless. There are always Outputfiles that seem to be "missing"

**Comment by marykthompson** [comment]
Hi, in the original error message you posted, I saw the error:  
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?

This is getting called in the choose_probes.py script, at the end of the pipeline. It looks like the pandas method DataFrame.append() is now deprecated, see here for alternatives: https://stackoverflow.com/questions/75956209/error-dataframe-object-has-no-attribute-append.

The easiest thing to do would be to downgrade your pandas to <2.0. It looks like I used pandas 1.0.3 when writing the paper (you can see the versions of all packages listed in Table S3 of the RNA paper). You should be able to downgrade pandas it in your current conda environment by using 'conda install pandas=1.0.3' but really I think any pandas <2.0 will probably work. I hope that will fix your issue!

**Comment by Aimepicornell** [comment]
Hey, this was actually the fix! Thank you soo much! I spend hours trying to find the error. Wish you all the best!

Aimé Picornell
